POST http://localhost:5002/videojuegos/actualizar
Content-Type: application/json

{
    "id" : "b9175dbc-d2ab-4771-ac3d-fe275e641bec",
    "nombre" : "Red Dead 2",
    "fecha" : "2025-11-14",
    "estado" : "Usado"
}
